name: Frontend Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  S3_BUCKET: fintrack-frontend-prod
  CF_DISTRIBUTION_ID: E1K4QMVPNMT5FU

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fintrack

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Debug working dir
        run: |
          echo "PWD: $(pwd)"
          ls -al
          echo "Find lockfile:"
          find . -maxdepth 2 -name package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: List build output
        run: ls -al dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: fintrack/dist

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::496669489645:role/FinTrackFrontendDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync static assets (cache forever)
        run: |
          aws s3 sync dist/ s3://$S3_BUCKET --delete \
            --exclude index.html \
            --exclude oidc-silent-redirect.html \
            --exclude vite.svg \
            --cache-control "public,max-age=31536000,immutable"

      - name: Upload HTML + short-cache files
        run: |
          aws s3 cp dist/index.html s3://$S3_BUCKET/index.html --cache-control "no-cache,max-age=0"
          if [ -f dist/oidc-silent-redirect.html ]; then
            aws s3 cp dist/oidc-silent-redirect.html s3://$S3_BUCKET/oidc-silent-redirect.html --cache-control "no-cache,max-age=0"
          fi
          if [ -f dist/vite.svg ]; then
            aws s3 cp dist/vite.svg s3://$S3_BUCKET/vite.svg --cache-control "public,max-age=31536000,immutable"
          fi

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CF_DISTRIBUTION_ID \
            --paths "/index.html" "/oidc-silent-redirect.html"
